### ISSUE TITLE
Fix ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by jimmyandrade** [multei/mobile#5]
When running `yarn test` on CircleCI or Travis, you find this:

```shell
#!/bin/bash -eo pipefail
yarn test
yarn run v1.10.1
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    ReferenceError: __DEV__ is not defined
```

```js
import 'react-native';
^

import React from 'react';
import App from '../App';
```

```shell
      at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native-implementation.js:353:1)
      at Object.<anonymous> (__tests__/App-test.js:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.33s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by jimmyandrade** [comment]
Closed by #7
